### ISSUE TITLE
Comparison with 3 properties

### ISSUE THREAD

**Issue by manowb** [AKSW/LIMES#19]
Hi everyone,

I think that with my current configuration file, LIMES can not compare resources with 3 properties (but it can do it with 2 properties). It generates no link.

Here is my configuration:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2010 rel. 3 sp1 (http://www.altova.com)-->
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/1999/02/22-rdf-syntax-ns#</NAMESPACE>
		<LABEL>rdf</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://model.org/</NAMESPACE>
		<LABEL>prop</LABEL>
	</PREFIX>
	<SOURCE>
		<ID>ontoA</ID>
		<ENDPOINT>C:/Users/Manel/Videos/OAEI/Test1/limes/person11.nt</ENDPOINT>
		<VAR>?a</VAR>
		<PAGESIZE>1000</PAGESIZE>
		<RESTRICTION>?a ?p1 ?c .</RESTRICTION>
		<PROPERTY>prop:property4</PROPERTY>
		<PROPERTY>prop:property3</PROPERTY>
		<PROPERTY>prop:property9</PROPERTY>
		<TYPE>N-TRIPLES</TYPE>
	</SOURCE>
	<TARGET>
		<ID>ontoB</ID>
		<ENDPOINT>C:/Users/Manel/Videos/OAEI/Test1/limes/person12.nt</ENDPOINT>
		<VAR>?b</VAR>
		<PAGESIZE>1000</PAGESIZE>
		<RESTRICTION>?b ?p2 ?c .</RESTRICTION>
		<PROPERTY>prop:property4</PROPERTY>
		<PROPERTY>prop:property3</PROPERTY>
		<PROPERTY>prop:property9</PROPERTY>
		<TYPE>N-TRIPLES</TYPE>
	</TARGET>
	<METRIC> AND ( levenshtein (a.prop:property4,b.prop:property4)|O.8, levenshtein (a.prop:property3,b.prop:property3)|O.8, levenshtein (a.prop:property9,b.prop:property9)|O.8)</METRIC>
	<ACCEPTANCE>
		<THRESHOLD>0.8</THRESHOLD>
		<FILE>ref.nt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</ACCEPTANCE>
	<REVIEW>
		<THRESHOLD>0.5</THRESHOLD>
		<FILE>reviewme.nt</FILE>
		<RELATION>owl:sameAs</RELATION>
	</REVIEW>
	<EXECUTION>Simple</EXECUTION>
	<OUTPUT>N-TRIPLES</OUTPUT>
</LIMES>
</xmp>
```

Did I do something wrong ? especially on : <METRIC> AND ( levenshtein (a.prop:property4,b.prop:property4)|O.8, levenshtein (a.prop:property3,b.prop:property3)|O.8, levenshtein (a.prop:property9,b.prop:property9)|O.8)</METRIC> ?

Thank you :)

**Comment by ngonga** [comment]
AND is a binary operator. Please check use AND(x, AND(y, z)).

**Comment by manowb** [comment]
Hi, thank you :) .... I just tried this one :
```xml
<METRIC> AND(levenshtein(a.prop:property4,b.prop:property4)|0.8, AND(levenshtein(a.prop:property3,b.prop:property3)|0.8, levenshtein(a.prop:property9,b.prop:property9)|0.8)). </METRIC>
```

And I got this error :

Exception in thread "main" java.lang.NumberFormatException: For input string: "0.8)."
        at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
        at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
        at java.lang.Double.parseDouble(Unknown Source)
        at de.uni_leipzig.simba.controller.Parser.getTerms(Parser.java:156)
        at de.uni_leipzig.simba.controller.Parser.<init>(Parser.java:26)
        at de.uni_leipzig.simba.mapper.SimpleSetConstraintsMapper.getLinks(SimpleSetConstraintsMapper.java:67)
        at de.uni_leipzig.simba.controller.PPJoinController.run(PPJoinController.java:161)
        at de.uni_leipzig.simba.controller.PPJoinController.main(PPJoinController.java:32)

Is this caused by the binary operation? Because with only 2 properties, it works well.

**Comment by ngonga** [comment]
You do not conform the operator specification. Use

AND(levenshtein(a.prop:property4,b.prop:property4)|0.8, AND(levenshtein(a.prop:property3,b.prop:property3)|0.8, levenshtein(a.prop:property9,b.prop:property9)|0.8)|0.8)

**Comment by manowb** [comment]
Thank you .... this solved my problem :)

Have a nice day,

Manel.
