### ISSUE TITLE
LinkedBrainz character problem

### ISSUE THREAD

**Issue by Zap123** [AKSW/LIMES#7]
Hello everyone, this may be stupid but I'm having this problem linking my dataset to LinkedBrainz. I think LIMES can not read this artist name http://musicbrainz.org/artist/b002cf3a-3fe2-4866-9a9a-fdd232a2c92f#_
Did I do something wrong or it's a LIMES' problem?

```
...
INFO [main] (SparqlQueryModule.java:145) - Getting statements 246000 to 247000
 WARN [main] (SparqlQueryModule.java:223) - Error while processing: ( ?y = <http://musicbrainz.org/artist/b002cf3a-3fe2-4866-9a9a-fdd232a2c92f#_> ) ( ?v0 = "^" ) -> [Root]
 WARN [main] (SparqlQueryModule.java:224) - Following exception occured: 0
java.lang.ArrayIndexOutOfBoundsException: 0
        at de.uni_leipzig.simba.preprocessing.Preprocessor.process(Preprocessor.java:23)
        at de.uni_leipzig.simba.query.SparqlQueryModule.fillCache(SparqlQueryModule.java:210)
        at de.uni_leipzig.simba.query.SparqlQueryModule.fillCache(SparqlQueryModule.java:38)
        at de.uni_leipzig.simba.cache.HybridCache.getData(HybridCache.java:249)
        at de.uni_leipzig.simba.cache.HybridCache.getData(HybridCache.java:218)
        at de.uni_leipzig.simba.controller.PPJoinController.run(PPJoinController.java:148)
        at de.uni_leipzig.simba.controller.PPJoinController.main(PPJoinController.java:32)
java -jar LIMES.jar g-linkedbrainz.xml  11,43s user 0,92s system 10% cpu 1:58,16 total
```

My configuration:
```XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE LIMES SYSTEM "limes.dtd">
<LIMES>
	<PREFIX>
		<NAMESPACE>http://www.w3.org/1999/02/22-rdf-syntax-ns#</NAMESPACE>
		<LABEL>rdf</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://xmlns.com/foaf/0.1/</NAMESPACE>
		<LABEL>foaf</LABEL>
	</PREFIX>
	<PREFIX>
		<NAMESPACE>http://purl.org/ontology/mo/</NAMESPACE>
		<LABEL>mo</LABEL>
	</PREFIX>
	<SOURCE>
		<ID>Artist</ID>
		<ENDPOINT>/opt/dataset.rdf</ENDPOINT>
		<VAR>?x</VAR>
		<PAGESIZE>5000</PAGESIZE>
		<RESTRICTION>?x rdf:type foaf:Agent. ?x foaf:homepage ?d</RESTRICTION>
		<PROPERTY>foaf:name</PROPERTY>
		<TYPE>RDF</TYPE>
	</SOURCE>
	<TARGET>
		<ID>linkedbrainz</ID>
		<ENDPOINT>http://linkedbrainz.org/sparql</ENDPOINT>
		<VAR>?y</VAR>
		<PAGESIZE>1000</PAGESIZE>
		<RESTRICTION>?y rdf:type mo:MusicArtist</RESTRICTION>
		<PROPERTY>foaf:name</PROPERTY>
	</TARGET>
	<METRIC>levenshstein(x.foaf:name,y.foaf:name)</METRIC>
	<ACCEPTANCE>
		<THRESHOLD>0.8</THRESHOLD>
		<FILE>musicbrainz.nt</FILE>
		<RELATION>rdf:about</RELATION>
	</ACCEPTANCE>
	<REVIEW>
		<THRESHOLD>0.5</THRESHOLD>
		<FILE>musicbrainz_reviewme.nt</FILE>
		<RELATION>rdf:about</RELATION>
	</REVIEW>
	<EXECUTION>OneToOne</EXECUTION>
	<OUTPUT>TTL</OUTPUT>
</LIMES>
```

**Comment by ngonga** [comment]
Try using &gt: for ">", etc.
